import re

file_path = "docs/superpowers/specs/2026-09-12-test-case-scaffolding-design.md"
with open(file_path, "r") as f:
    code = f.read()

old_tree = """```text
data/
  ├── secure/                             <-- DANGER: Contains PII. 
  │   ├── interview_01.json               <-- The raw input you drop in
  │   └── interview_01_reconstituted.json <-- The final usable KG with PII re-injected
  │
  └── working/                            <-- SAFE: Zero PII. Intermediate processing.
      ├── scrubbed_inputs/                
      │   └── interview_01.json           <-- The anonymized transcript
      └── evaluations/            
          └── interview_01/               <-- Autogenerated artifact folder
              ├── answer_key.json         <-- Generated Ground Truth
              ├── kg_naive.json           <-- Naive baseline output
              ├── kg_rlms.json            <-- Standard RLM output
              └── kg_propositional.json   <-- Propositional hybrid output
```"""

new_tree = """```text
data/
  ├── secure/                             
  │   ├── inputs/
  │   │   └── interview_01.json               
  │   └── reconstituted/
  │       └── interview_01/
  │           ├── kg_naive_2026-09-12_gemma4.json
  │           ├── kg_rlms_2026-09-12_gemma4.json
  │           └── kg_propositional_2026-09-12_gemma4.json
  │
  └── working/                            
      ├── scrubbed_inputs/                
      │   └── interview_01.json           
      └── evaluations/            
          └── interview_01/               
              ├── answer_key.json                           <-- Ground truth (Run once, shared)
              ├── kg_naive_2026-09-12_gemma4.json           
              ├── kg_rlms_2026-09-12_gemma4.json            
              ├── kg_propositional_2026-09-12_gemma4.json   
              └── leaderboard_2026-09-12_gemma4.md          <-- Saved locally
```"""

code = code.replace(old_tree, new_tree)

with open(file_path, "w") as f:
    f.write(code)
print("Patched spec.")
